TRAIN:
  MAX_ITER: 30000
MODEL:
  PRETRAINED: True
  NUM_CLASSES: 101
OPTIMIZER:
  NAME: 'sgd'
  LR: 2e-3
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  WARMUP: True
DATALOADER:
  TRAIN_BATCH_SIZE: 64
  TEST_BATCH_SIZE: 64
DATASETS:
  TRAIN:
    NAME: 'UCF101'
    SPLITS: (1, 2, 3)
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
  TEST:
    NAME: 'UCF101'
    SPLITS: (1, 2, 3)
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
OUTPUT:
  DIR: 'outputs/resnet50_ucf101'