TRAIN:
  MAX_ITER: 30000
MODEL:
  PRETRAINED: True
OPTIMIZER:
  NAME: 'sgd'
  LR: 2e-3
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  WARMUP: True
DATALOADER:
  TRAIN_BATCH_SIZE: 64
  TEST_BATCH_SIZE: 64