RNG_SEED: 0
NUM_GPUS: 1
NODES: 1
RANK: 0
WORLD_SIZE: 1
TRAIN:
  MAX_ITER: 30000
  LOG_STEP: 10
  SAVE_STEP: 1000
  EVAL_STEP: 1000
  RESUME: False
  USE_TENSORBOARD: True
OUTPUT:
  DIR: 'outputs/tsn_r50_ucf101_rgb_224x3_seg'
DATASETS:
  MODALITY: 'RGB'
  SAMPLE_STRATEGY: 'SegSample'
  CLIP_LEN: 1
  FRAME_INTERVAL: 1
  NUM_CLIPS: 3
  TRAIN:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
  TEST:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
TRANSFORM:
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  JITTER_SCALES: (256, 320)
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  RANDOM_ROTATION: 10
  COLOR_JITTER: (0.1, 0.1, 0.1, 0.1)
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  NAME: 'TSN'
  PRETRAINED: ''
  SYNC_BN: True
  INPUT_SIZE: (224, 224, 3)
  BACKBONE:
    NAME: 'resnet50'
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: True
    ZERO_INIT_RESIDUAL: True
  HEAD:
    NAME: 'TSNHead'
    FEATURE_DIMS: 2048
    DROPOUT: 0.0
    NUM_CLASSES: 101
  RECOGNIZER:
    NAME: 'TSNRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'crossentropy'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-3
  WEIGHT_DECAY: 1e-4
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  IS_WARMUP: True
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 1e-4
  WARMUP:
    ITERATION: 400
    MULTIPLIER: 1.0
DEMO:
  ENABLE: True
  INPUT_VIDEO: './data/ucf101/videos/YoYo/v_YoYo_g18_c04.avi'
  #  OUTPUT_FILE: './outputs/YoYo_output.avi'
  LABEL_FILE_PATH: './data/ucf101/annotations/class2idx.json'