DATASETS:
  MODALITY: 'RGBDiff'
  NUM_SEGS: 3
  TRAIN:
    NAME: 'HMDB51'
    DATA_DIR: 'data/hmdb51/rawframes'
    ANNOTATION_DIR: 'data/hmdb51'
    SPLIT: 1
  TEST:
    NAME: 'HMDB51'
    DATA_DIR: 'data/hmdb51/rawframes'
    ANNOTATION_DIR: 'data/hmdb51'
    SPLIT: 1
TRANSFORM:
  INPUT_SIZE: (224, 224, 3)
  SMALLER_EDGE: 256
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
DATALOADER:
  TRAIN_BATCH_SIZE: 16
  TEST_BATCH_SIZE: 16
  NUM_WORKERS: 8
MODEL:
  PRETRAINED: ""
  SYNC_BN: True
  BACKBONE:
    NAME: 'resnet50'
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: True
  HEAD:
    NAME: 'TSNHead'
    FEATURE_DIMS: 2048
    DROPOUT: 0.0
    NUM_CLASSES: 51
  RECOGNIZER:
    NAME: 'TSNRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'crossentropy'
OPTIMIZER:
  NAME: 'adam'
  LR: 3e-4
  WEIGHT_DECAY: 3e-5
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  IS_WARMUP: True
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 3e-4
  WARMUP:
    ITERATION: 1000
    MULTIPLIER: 1.0
TRAIN:
  MAX_ITER: 30000
OUTPUT:
  DIR: 'outputs/tsn_resnet50_hmdb51_rgb_224x224x3'