NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/tsn_r50_hmdb51_rgbdiff_raw_seg_1x1x3'
TRAIN:
  MAX_ITER: 20000
  LOG_STEP: 10
  SAVE_STEP: 1000
  EVAL_STEP: 1000
  RESUME: False
  USE_TENSORBOARD: True
DATASETS:
  MODALITY: 'RGBDiff'
  TYPE: 'RawFrame'
  SAMPLE_STRATEGY: 'SegSample'
  CLIP_LEN: 5
  FRAME_INTERVAL: 1
  NUM_CLIPS: 3
  TRAIN:
    NAME: 'HMDB51'
    DATA_DIR: 'data/hmdb51/rawframes'
    ANNOTATION_DIR: 'data/hmdb51'
    SPLIT: 1
  TEST:
    NAME: 'HMDB51'
    DATA_DIR: 'data/hmdb51/rawframes'
    ANNOTATION_DIR: 'data/hmdb51'
    SPLIT: 1
TRANSFORM:
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  SCALE_JITTER: (256, 320)
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  RANDOM_ROTATION: 10
  COLOR_JITTER: (0.1, 0.1, 0.1, 0.1)
DATALOADER:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
  NUM_WORKERS: 8
MODEL:
  NAME: 'TSN'
  PRETRAINED: ""
  SYNC_BN: True
  INPUT_SIZE: (224, 224, 3)
  BACKBONE:
    NAME: 'resnet50'
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: True
    ZERO_INIT_RESIDUAL: True
  HEAD:
    NAME: 'TSNHead'
    FEATURE_DIMS: 2048
    DROPOUT: 0.0
    NUM_CLASSES: 51
  RECOGNIZER:
    NAME: 'TSNRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'sgd'
  LR: 2e-3
  WEIGHT_DECAY: 1e-4
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  IS_WARMUP: True
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 3e-4
  WARMUP:
    ITERATION: 1000
    MULTIPLIER: 1.0