DATASETS:
  MODALITY: 'RGB'
  NUM_SEGS: 3
  TRAIN:
    NAME: 'HMDB51'
    DATA_DIR: 'data/hmdb51/rawframes'
    ANNOTATION_DIR: 'data/hmdb51'
    SPLIT: 1
  TEST:
    NAME: 'HMDB51'
    DATA_DIR: 'data/hmdb51/rawframes'
    ANNOTATION_DIR: 'data/hmdb51'
    SPLIT: 1
TRANSFORM:
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  JITTER_SCALES: (256, 320)
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  NAME: 'TSN'
  PRETRAINED: ""
  SYNC_BN: False
  INPUT_SIZE: (224, 224, 3)
  BACKBONE:
    NAME: 'resnet50'
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: True
  HEAD:
    NAME: 'TSNHead'
    FEATURE_DIMS: 2048
    DROPOUT: 0.0
    NUM_CLASSES: 51
  RECOGNIZER:
    NAME: 'TSNRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'crossentropy'
OPTIMIZER:
  NAME: 'sgd'
  LR: 2e-3
  WEIGHT_DECAY: 3e-4
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  IS_WARMUP: True
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 3e-4
  WARMUP:
    ITERATION: 400
    MULTIPLIER: 1.0
TRAIN:
  MAX_ITER: 10000
OUTPUT:
  DIR: 'outputs/tsn_r50_hmdb51_rgb_224x224x3'